INSERT INTO series (title, author_id, subgenre_id) VALUES ('fiction', 1, 1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ('xxx', 2, 2);
INSERT INTO books (title, year, series_id) VALUES ('title1', 1987, 2);
INSERT INTO books (title, year, series_id) VALUES ('title2', 1989, 3);
INSERT INTO books (title, year, series_id) VALUES ('title3', 1999, 4);
INSERT INTO books (title, year, series_id) VALUES ('title1', 2000, 5);
INSERT INTO books (title, year, series_id) VALUES ('title1', 2003, 6);
INSERT INTO books (title, year, series_id) VALUES ('title1', 2003, 9);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Tom', 'dog', 'woof', 1);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Jerry', 'dog', 'xxx', 8);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Merry', 'human', 'sss', 7);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Dan', 'cat', 'ddd', 5);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Doug', 'mouse', 'aaa', 6);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Sam', 'dog', 'lll', 4);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Ben', 'human', 'ppp', 3);
INSERT INTO characters (name, species, motto, author_id) VALUES ('Jerry', 'cat', 'ooo', 2);
INSERT INTO subgenres (name) VALUES ('nnn');
INSERT INTO subgenres (name) VALUES ('xxx');
INSERT INTO authors (name) VALUES ('Dan');
INSERT INTO authors (name) VALUES ('Sam');
INSERT INTO character_books (book_id, character_id) VALUES (1, 1); 
INSERT INTO character_books (book_id, character_id) VALUES (1, 2);
INSERT INTO character_books (book_id, character_id) VALUES (1, 3);
INSERT INTO character_books (book_id, character_id) VALUES (1, 4);
INSERT INTO character_books (book_id, character_id) VALUES (2, 1);
INSERT INTO character_books (book_id, character_id) VALUES (2, 2);
INSERT INTO character_books (book_id, character_id) VALUES (2, 3);
INSERT INTO character_books (book_id, character_id) VALUES (2, 4);
INSERT INTO character_books (book_id, character_id) VALUES (3, 1);
INSERT INTO character_books (book_id, character_id) VALUES (3, 2);
INSERT INTO character_books (book_id, character_id) VALUES (3, 3);
INSERT INTO character_books (book_id, character_id) VALUES (3, 4);
INSERT INTO character_books (book_id, character_id) VALUES (4, 1);
INSERT INTO character_books (book_id, character_id) VALUES (4, 2);
INSERT INTO character_books (book_id, character_id) VALUES (4, 3);
INSERT INTO character_books (book_id, character_id) VALUES (4, 4);